import React from 'react';
import { MessageCircle, MessageSquare, Users, Mic, Image as ImageIcon, Archive, Calendar, Clock, BarChart2 } from 'lucide-react';

interface DashboardImageProps {
  data: {
    totalConversations: number;
    totalMessages: number;
    totalGPTConversations: number;
    totalVoiceMessages: number;
    totalImagesGenerated: number;
    totalArchivedConversations: number;
    mostChattyDay: { count: number; date: string };
    timeSpentOnChatGPT: { days: number };
    averageDailyMessageCount: number;
  };
}

const MetricCard: React.FC<{ title: string; value: string | number; icon: React.ReactNode }> = ({ title, value, icon }) => (
  <div className="bg-white/5 border border-white/10 backdrop-blur-sm rounded-2xl p-6 flex items-center justify-between transition-all hover:bg-white/10">
    <div className="flex flex-col">
      <h3 className="text-sm font-semibold mb-2 text-gray-400 uppercase tracking-wider">{title}</h3>
      <p className="text-3xl font-bold text-white tracking-tight">{value}</p>
    </div>
    <div className="p-3 bg-white/5 rounded-xl">
    {React.cloneElement(icon as React.ReactElement<{ size?: number }>, { size: 28 })}
    </div>
  </div>
);

const DashboardImage: React.FC<DashboardImageProps> = ({ data }) => {
  return (
    <div 
      className="bg-[#0a0a0a] p-12 flex flex-col justify-between" 
      style={{ width: '1200px', height: '630px', fontFamily: 'Inter, system-ui, sans-serif' }}
    >
      {/* Background Glows for subtle style improvement */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden -z-10 opacity-30">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-blue-500/20 rounded-full blur-[100px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-purple-500/20 rounded-full blur-[100px]" />
      </div>

      <h1 className="text-4xl font-extrabold text-center text-white mb-10 tracking-tight">
        ChatGPT Review
      </h1>

      <div className="grid grid-cols-3 gap-6 flex-grow">
        <MetricCard title="Total Conversations" value={data.totalConversations} icon={<MessageCircle className="text-blue-400" />} />
        <MetricCard title="Total Messages" value={data.totalMessages.toLocaleString()} icon={<MessageSquare className="text-indigo-400" />} />
        <MetricCard title="Total GPTs Used" value={data.totalGPTConversations} icon={<Users className="text-purple-400" />} />
        <MetricCard title="Total Voice Messages" value={data.totalVoiceMessages} icon={<Mic className="text-pink-400" />} />
        <MetricCard title="Total Images Generated" value={data.totalImagesGenerated} icon={<ImageIcon className="text-yellow-400" />} />
        <MetricCard title="Total Archived Conversations" value={data.totalArchivedConversations} icon={<Archive className="text-red-400" />} />
        <MetricCard title="Most Chatty Day" value={`${data.mostChattyDay.count} (${data.mostChattyDay.date})`} icon={<Calendar className="text-green-400" />} />
        <MetricCard title="Time Spent on ChatGPT" value={`${data.timeSpentOnChatGPT.days.toFixed(2)} days`} icon={<Clock className="text-blue-400" />} />
        <MetricCard title="Average Daily Message" value={data.averageDailyMessageCount.toFixed(2)} icon={<BarChart2 className="text-teal-400" />} />
      </div>

      <div className="mt-8 text-center font-bold text-white/30 tracking-widest uppercase text-xs">
        Generated by: Convelyze (convelyze.pages.dev)
      </div>
    </div>
  );
};

export default DashboardImage;
