import React from 'react';
import { MessageCircle, MessageSquare, Users, Mic, Image as ImageIcon, Archive, Calendar, Clock, BarChart2 } from 'lucide-react';

interface DashboardImageProps {
  data: {
    totalConversations: number;
    totalMessages: number;
    totalGPTConversations: number;
    totalVoiceMessages: number;
    totalImagesGenerated: number;
    totalArchivedConversations: number;
    mostChattyDay: { count: number; date: string };
    timeSpentOnChatGPT: { days: number };
    averageDailyMessageCount: number;
  };
}

const MetricCard: React.FC<{ title: string; value: string | number; icon: React.ReactNode }> = ({ title, value, icon }) => (
  <div className="bg-gray-800 rounded-lg shadow-md p-6 flex items-center justify-between">
    <div className="flex flex-col">
      <h3 className="text-lg font-semibold mb-2 text-gray-300">{title}</h3>
      <p className="text-3xl font-bold text-white">{value}</p>
    </div>
    <div className="text-4xl text-gray-300">{icon}</div>
  </div>
);

const DashboardImage: React.FC<DashboardImageProps> = ({ data }) => {
  return (
    <div className="bg-gray-900 p-10 rounded-lg" style={{ width: '1200px', height: '630px' }}>
      <h1 className="text-4xl font-bold text-center mb-8 text-white">ChatGPT Dashboard</h1>
      <div className="grid grid-cols-3 gap-8 h-[calc(100%-6rem)]">
        <MetricCard title="Total Conversations" value={data.totalConversations} icon={<MessageCircle className="text-blue-400" />} />
        <MetricCard title="Total Messages" value={data.totalMessages} icon={<MessageSquare className="text-indigo-400" />} />
        <MetricCard title="Total GPTs Used" value={data.totalGPTConversations} icon={<Users className="text-purple-400" />} />
        <MetricCard title="Total Voice Messages" value={data.totalVoiceMessages} icon={<Mic className="text-pink-400" />} />
        <MetricCard title="Total Images Generated" value={data.totalImagesGenerated} icon={<ImageIcon className="text-yellow-400" />} />
        <MetricCard title="Total Archived Conversations" value={data.totalArchivedConversations} icon={<Archive className="text-red-400" />} />
        <MetricCard title="Most Chatty Day" value={`${data.mostChattyDay.count} (${data.mostChattyDay.date})`} icon={<Calendar className="text-green-400" />} />
        <MetricCard title="Time Spent on ChatGPT" value={`${data.timeSpentOnChatGPT.days.toFixed(2)} days`} icon={<Clock className="text-blue-400" />} />
        <MetricCard title="Average Daily Message" value={data.averageDailyMessageCount.toFixed(2)} icon={<BarChart2 className="text-teal-400" />} />
      </div>
      <div style={{ marginTop: '20px', textAlign: 'center', fontStyle: 'bold' }}>
        Generated by: Convelyze (convelyze.pages.dev)
      </div>
    </div>
  );
};

export default DashboardImage;